In [1]:
import tensorflow as tf
import numpy as np

# 创建

## From Numpy List

|函数|说明|
|:----|:----|
|tf.constant()|将对象转换为tensor|
|tf.convert_to_tensor()|同上|

In [2]:
tf.convert_to_tensor(np.ones([2,3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [3]:
tf.constant([1,2.])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

## From TF

|函数|说明|
|:----|:----|
|tf.zeros([shape])|创建shape的全0 Tensor|
|tf.zeros_like([Tensor])|获取Tensor的shape 创建全0 Tensor|
|tf.ones([shape])|创建shape的全1 Tensor|
|tf.ones_like([Tensor])|获取Tensor的shape 创建1 Tensor|
|tf.fill([shape],[n])|创建shape的Tensor 以n填充|
|tf.range([n])|同range|
|tf.random.normal([shape],mean=[mean],stddev=[stddev])|创建shape的Tensor 随机填充|
|tf.random.truncated_normal([shape],mean=[mean],stddev=[stddev])|截断的数据|
|tf.random.uniform([shape],minval=[minval],maxval=[maxval])|均匀分布|
|tf.random.shuffle([Tensor])|打乱 洗牌|

In [4]:
tf.random.normal([2,2],mean=1,stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7269063 , -0.20977914],
       [-0.6060593 ,  2.0158367 ]], dtype=float32)>

In [5]:
tf.random.truncated_normal([2,2],mean=0,stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.1838137 ,  0.25277877],
       [-0.4281667 , -1.9225777 ]], dtype=float32)>

In [6]:
tf.random.uniform([2,2],minval=0,maxval=1) 

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.93980443, 0.63926625],
       [0.64218485, 0.6706773 ]], dtype=float32)>

## Loss

In [7]:
y = tf.range(4)
y = tf.one_hot(y,depth=10)
out = tf.random.uniform([4,10])
loss = tf.keras.losses.mse(y,out)

In [8]:
loss

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.32718024, 0.28491095, 0.4561185 , 0.16287963], dtype=float32)>

In [9]:
loss.numpy().mean()

0.3077723

In [10]:
tf.reduce_mean(loss)

<tf.Tensor: shape=(), dtype=float32, numpy=0.30777234>

## Vector

In [11]:
net = tf.keras.layers.Dense(10)
net.build((4,8))
net.kernel.shape

TensorShape([8, 10])

In [12]:
net.bias

<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

## Matrix

In [13]:
x = tf.random.normal([4,784])
x.shape

TensorShape([4, 784])

In [14]:
net = tf.keras.layers.Dense(10)
net.build((4,784))

net(x).shape

TensorShape([4, 10])

In [15]:
net.kernel.shape

TensorShape([784, 10])

In [16]:
net.bias.shape

TensorShape([10])

In [17]:
x = tf.random.normal([4,28,28,3])
net = tf.keras.layers.Conv2D(16,kernel_size=3)
net(x).shape

TensorShape([4, 26, 26, 16])

# 变形

|函数|说明|
|:----|:----|
|tf.gather([Tensor],axis=[axis],indices=[indices])|索引|
|tf.gather_nd([Tensor],indices=[indices])|索引|
|tf.boolean_mask([Tensor],mask=[True,False,...],axis=[axis])|根据mask在axis轴进行mask|
|tf.reshape([Tensor],[shape])|改变Tensor的shape|
|tf.transpose([Tensor])|将Tensor转至|
|tf.expand_dims([Tensor],axis=[axis])|增加维度|
|tf.squeeze([Tensor])|删除值为1的维度|
|tf.broadcast_to([Tensor],[shape])|将Tensor广播至shape|
|tf.title([Tensor],[multiples])|Tensor沿axis铺(复制)multiples倍|

## tf.gather

In [18]:
a = tf.random.uniform((4,35,8),minval=0,maxval=10,dtype=tf.int32)

In [19]:
tf.gather(a,indices=[2,3]).shape

TensorShape([2, 35, 8])

In [20]:
tf.gather_nd(a,indices=[2,3]).shape

TensorShape([8])

## tf.boolean_mask

In [21]:
tf.boolean_mask(a,mask=[True,True,False,False],axis=0).shape

TensorShape([2, 35, 8])

In [22]:
tf.boolean_mask(a,mask=[True,True,False,False,True,True,False,False],axis=2).shape

TensorShape([4, 35, 4])

## tf.reshape

In [23]:
img = tf.random.normal([4,28,28,3])
img.shape, img.ndim

(TensorShape([4, 28, 28, 3]), 4)

In [24]:
tf.reshape(img,[4,28*28,3]).shape

TensorShape([4, 784, 3])

In [25]:
tf.reshape(img,[4,-1,3]).shape

TensorShape([4, 784, 3])

In [26]:
tf.reshape(img,[4,-1]).shape

TensorShape([4, 2352])

## tf.expand_dims

In [27]:
a = tf.random.normal([4,35,8])

In [28]:
tf.expand_dims(a,axis=0).shape

TensorShape([1, 4, 35, 8])

In [29]:
tf.expand_dims(a,axis=3).shape

TensorShape([4, 35, 8, 1])

## Broadcasting

In [30]:
a = tf.random.uniform((2,3,3),minval=1,maxval=10,dtype=tf.int32)
b = tf.random.uniform((3,3),minval=1,maxval=3,dtype=tf.int32)

In [31]:
a.shape, b.shape

(TensorShape([2, 3, 3]), TensorShape([3, 3]))

In [32]:
tf.broadcast_to(b,a.shape).shape  # 高效  使用更小的内存

TensorShape([2, 3, 3])

In [33]:
tf.tile(tf.expand_dims(b,axis=0),[2,1,1]).shape

TensorShape([2, 3, 3])

In [34]:
tf.tile(b,[2,1]).shape

TensorShape([6, 3])

# 计算

|函数|说明|
|:----|:----|
|tf.add([Tensor],[Tensor])/tf.math.add([Tensor],[Tensor])|加减|
|tf.pow([Tensor],[n])/tf.math.pow([Tensor],[n])|n乘|
|tf.sqrt([Tensor])/tf.math.sqrt([Tensor])|平方根|
|tf.math.log([Tensor])|log底数为10|
|tf.exp[Tensor])/tf.math.exp([Tensor])|自然底数|
|tf.matmul([Tensor],[Tensor])/a@b|点积|

In [35]:
a = tf.fill((2,2),2.)   
b = tf.ones([2,2])

In [36]:
a+b , a-b , a*b,a/b ,a//b , b%a # dtype 需要相等

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[3., 3.],
        [3., 3.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>)

In [37]:
tf.math.log(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.6931472, 0.6931472],
       [0.6931472, 0.6931472]], dtype=float32)>

In [38]:
tf.exp(a),tf.math.exp(a)

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[7.389056, 7.389056],
        [7.389056, 7.389056]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[7.389056, 7.389056],
        [7.389056, 7.389056]], dtype=float32)>)

In [39]:
tf.math.log(8.)/tf.math.log(2.)  # 底数为2

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [40]:
tf.pow(a,2), tf.math.pow(a,2),a**2

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[4., 4.],
        [4., 4.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[4., 4.],
        [4., 4.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[4., 4.],
        [4., 4.]], dtype=float32)>)

In [41]:
tf.sqrt(a),tf.math.sqrt(a)

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1.4142134, 1.4142134],
        [1.4142134, 1.4142134]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1.4142134, 1.4142134],
        [1.4142134, 1.4142134]], dtype=float32)>)

In [42]:
tf.matmul(a,b), a@b

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[4., 4.],
        [4., 4.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[4., 4.],
        [4., 4.]], dtype=float32)>)

In [43]:
x = tf.ones([4,2])
w = tf.ones([2,1])
b = tf.constant(0.1)

In [44]:
x@w+b

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[2.1],
       [2.1],
       [2.1],
       [2.1]], dtype=float32)>

In [45]:
tf.nn.relu(x@w+b)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[2.1],
       [2.1],
       [2.1],
       [2.1]], dtype=float32)>